### PR TITLE
Update project and fix the feed parsing issue

### PR DESCRIPTION
**Pull request by cwilson**
This is a fix for https://github.com/manmal/hn-android/issues/189.

This PR updates the project to use Android 32 and more recent Gradle version. I'm not an Android developer so it could probably use some more experienced eyes on it.

First and 3rd commit are upgrading Android SDK, Gradle and other dependencies. The code in app/build.gradle around building variants wasn't working so I removed it -- someone can probably comment whether it's necessary.

Second commit is to fix issues when parsing the HN feed. I'm not sure what changed in the markup but using class selectors instead of tag position selectors fixes the problem.

### CODE REVIEW

**Comment by manmal** [comment]
Thanks for the PR @cwilson, we'll look at it over the weekend!

**Comment by manmal** [comment]
Hey @cwilson,
Congratulations, you brought back the app with this PR! 🎉 We are in the process of finishing up and then uploading the new build to the Play Store. If you ever come to Vienna (AT), ping me on Twitter (@manuelmaly) and I'll buy you a beer or coffee.

Thanks for your effort! 🙌

**Comment by cwilson** [comment]
Thanks @manmal, glad to help!

**Comment by heikoengel** [comment]
Hey @manmal,
thanks a lot for pushing the update to the Play Store! Do you think it would be possible to provide the new version also via F-Droid?
https://f-droid.org/en/packages/com.manuelmaly.hn/
Thanks!

**Comment by manmal** [comment]
Hey @heikoengel, I don't have the capacity right now to get involved with f-droid, but you are welcome do dig into it. In 2013, David Black (from the f-droid Maintainers) put the app up there.

**Comment by heikoengel** [comment]
It worked, the new version is also on F-Droid now!

**Comment by manmal** [comment]
Awesome, glad to learn that!

**Pull request merged**
