### PR TITLE
Pull down to refresh

### PR DESCRIPTION
**Pull request by tbroadley**
This is the pull request for the "pull down to refresh" feature discussed in #163.

Currently it is not ready for merging. This is just to help keep track of it!

### CODE REVIEW

**Comment by tbroadley** [comment]
Laying some groundwork. I'm away for the weekend - looking forward to tackle this again on Sunday night or Monday. :smile:

**Comment by peshkira** [comment]
Looking good! Thanks! Have a great weekend.

**Comment by tbroadley** [comment]
@peshkira, I wonder if both refresh options should be available at the same time. If a user is all the way down the posts feed or comment page, it would be easier to reload with the menu button. What do you think?

**Comment by peshkira** [comment]
@tbroadley Yes, I think it is better to keep it. We don't have so many options there, so I'd keep it in the overflow as well.

**Comment by tbroadley** [comment]
Agreed! It's changed in the above commit.

**Comment by tbroadley** [comment]
Okay, I believe it is finished. I've only tested it on an emulator running API level 23 - I would like to test it on a couple of older versions as well.

**Comment by tbroadley** [comment]
I tested it on an API level 19 emulator as well. I think that it is ready to be merged!

**Comment by tbroadley** [comment]
@peshkira let me know if you have a moment to take a look at this. :)

**Comment by peshkira** [comment]
@tbroadley Thanks again for this PR. I tested it and it works good. I am not sure if people will accept the pull to refresh in the article activity as the indicator stays too long over the content, but let's give it a go. After all it is in the google guidelines ;).

I'll inspect the other PRs and try to release asap.

**Comment by tbroadley** [comment]
Thank you for testing it! I noticed that too, the loading icon does stick around for a while over the article... I don't think it goes away until the page is fully rendered. I couldn't find a callback method for when all the assets are loaded, sadly.





On Mon, Oct 19, 2015 at 1:49 PM -0700, "Petar Petrov" <notifications@github.com> wrote:
@tbroadley Thanks again for this PR. I tested it and it works good. I am not sure if people will accept the pull to refresh in the article activity as the indicator stays too long over the content, but let's give it a go. After all it is in the google guidelines ;).

I'll inspect the other PRs and try to release asap.

---

**Pull request merged**
